# Generated by Django 4.2.1 on 2023-05-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='date_added',
        ),
    ]
