databases:
  - name: django_pos
    databaseName: django_pos
    user: django_pos

services:
  - type: web
    name: django_pos
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_pos.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_pos
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
        
static_dirs:
- staticfiles
- media