# Generated by Django 4.2.1 on 2023-05-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name_plural': 'Shops'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='shop',
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='Active', max_length=100, verbose_name='Status of the shop'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employees',
        ),
        migrations.AlterModelTable(
            name='shop',
            table='Shop',
        ),
    ]
