# Generated by Django 4.2.1 on 2023-05-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetail',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='user',
        ),
    ]
