# Generated by Django 4.2.1 on 2023-05-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_group_alter_expense_category_delete_xcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capital',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='group',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
