# Generated by Django 4.2.1 on 2023-05-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_purchasedetail_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
