# Generated by Django 4.2.1 on 2023-05-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchasedetail_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
