# Generated by Django 4.2.5 on 2023-09-10 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_purchasedetail_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(db_column='purchase', on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase'),
        ),
    ]
