# Generated by Django 4.2.1 on 2023-05-10 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_alter_sector_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name_plural': 'Sectors'},
        ),
        migrations.AlterField(
            model_name='production',
            name='sector',
            field=models.ForeignKey(db_column='sector', on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='productions.sector'),
        ),
    ]
