# Generated by Django 4.2.1 on 2023-05-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0004_rename_receivedby_production_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='employee',
        ),
    ]
