# Generated by Django 4.2.1 on 2023-05-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_category_options_alter_product_status'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=256)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=100, verbose_name='Status of the sector')),
            ],
            options={
                'verbose_name_plural': 'Sectors',
                'db_table': 'Sector',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
                ('receivedby', models.ForeignKey(db_column='employee', on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee')),
                ('sector', models.ForeignKey(db_column='Sector', on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='productions.sector')),
            ],
            options={
                'db_table': 'Production',
            },
        ),
    ]
