# Generated by Django 4.2.1 on 2023-05-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name_plural': 'sectors'},
        ),
    ]
