# Generated by Django 4.2.1 on 2023-05-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_venta_saledetail_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
